name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get release title
      run: |
        RELEASE_TITLE=$(echo "${GITHUB_RELEASE}" | jq -r '.name')
        echo "::set-env name=RELEASE_TITLE::${RELEASE_TITLE}"
    - name: Set GITHUB_REPO
      run: |
        echo "::set-env name=GITHUB_REPO::${GITHUB_REPOSITORY}"
    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${GITHUB_REPO}/$RELEASE_TITLE
        docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        docker push ghcr.io/${GITHUB_REPO}/$RELEASE_TITLE
    - name: Update release assets
      run: |
        curl -X PATCH \
          https://api.github.com/repos/${GITHUB_REPO}/releases/${GITHUB_RELEASE_ID} \
          -H 'Authorization: Bearer $GITHUB_TOKEN' \
          -H 'Content-Type: application/json' \
          -d '{"assets": [{"name": "docker-image", "label": "Docker Image", "url": "ghcr.io/${GITHUB_REPO}/$RELEASE_TITLE"}]}'
